# backend/services/export.py
"""
Packing a generated project into a zip for download.

The deliverable of this product is a working project, so "Download" is not a nicety - it is
how the value leaves the app. The zip is built in memory because these projects are small
(tens of kilobytes of source) and a temp file would add cleanup that can fail.

Two details that matter more than they look:

**Nothing is read from disk.** The archive is assembled from the :class:`GeneratedProject`
itself, so a download cannot accidentally include a sandbox artefact, a ``.env`` written
during a test run, or a ``__pycache__`` directory from an execution. What the user sees in
the Files tab is exactly what they get.

**A fixed timestamp for every entry.** ``ZipInfo`` defaults to "now", which would make two
downloads of an unchanged project produce different bytes. A constant makes the output
reproducible, which is what lets a user diff two downloads and see only real changes.
"""
from __future__ import annotations

import io
import posixpath
import re
import zipfile
from typing import Optional

from multi_agent_generator.core.models import GeneratedProject

__all__ = ["project_zip_bytes", "suggest_filename"]

#: A fixed date-time for every archive member, so identical input yields identical bytes.
#: 1980-01-01 is the earliest value the zip format can represent.
_FIXED_DATE = (1980, 1, 1, 0, 0, 0)


def project_zip_bytes(
    project: GeneratedProject,
    *,
    root: Optional[str] = None,
    include_readme: bool = True,
) -> bytes:
    """
    Build a zip archive of ``project``.

    Args:
        project: the project to pack.
        root: a top-level directory inside the archive. Present by default because
            extracting an archive that scatters twenty files into the current directory is a
            hostile thing to do to someone's Downloads folder.
        include_readme: add a README describing how to run the project, when the generator
            did not already produce one.

    Returns:
        The archive as bytes, ready to stream.
    """
    folder = _safe_folder(root or f"{project.framework or 'agent'}-project")
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for generated in project.files:
            _write(archive, posixpath.join(folder, generated.path), generated.content)

        existing = {f.path.lower() for f in project.files}

        if "requirements.txt" not in existing and project.dependencies:
            # The project is not runnable without its dependency list, and a generator that
            # omitted the file should not cost the user a broken download.
            body = "\n".join(project.dependencies) + "\n"
            _write(archive, posixpath.join(folder, "requirements.txt"), body)

        if include_readme and "readme.md" not in existing:
            _write(archive, posixpath.join(folder, "README.md"), _readme(project))

    return buffer.getvalue()


def _write(archive: zipfile.ZipFile, name: str, content: str) -> None:
    info = zipfile.ZipInfo(filename=name, date_time=_FIXED_DATE)
    # 0o644, shifted into the high bits where zip keeps unix permissions. Without this the
    # extracted files have no mode bits on unix and land as 000.
    info.external_attr = 0o644 << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    archive.writestr(info, content)


def _readme(project: GeneratedProject) -> str:
    entry = project.entrypoint_file
    lines = [
        f"# {project.framework or 'Agent'} project",
        "",
        "Generated by multi-agent-generator.",
        "",
        "## Setup",
        "",
        "```bash",
        "python -m venv .venv",
        "source .venv/bin/activate    # Windows: .venv\\Scripts\\activate",
        "pip install -r requirements.txt",
        "```",
        "",
        "## Configure",
        "",
        f"This project calls **{project.provider or 'an LLM provider'}**"
        f"{f' using `{project.model}`' if project.model else ''}.",
        "Set its API key as an environment variable before running - the key is read from the",
        "environment and is deliberately not written into the source.",
        "",
        "## Run",
        "",
    ]
    if project.run_instructions:
        lines += [project.run_instructions, ""]
    elif entry is not None:
        lines += ["```bash", f"python {entry.path}", "```", ""]

    if project.test_files():
        lines += [
            "## Test",
            "",
            "The bundled tests run offline - they do not call the provider and need no key.",
            "",
            "```bash",
            "pip install pytest",
            "pytest",
            "```",
            "",
        ]

    if project.notes:
        lines += ["## Notes", ""] + [f"- {note}" for note in project.notes] + [""]

    return "\n".join(lines)


def _safe_folder(raw: str) -> str:
    """A single, filesystem-safe directory name for the archive root."""
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", str(raw or "").strip()).strip("-.")
    return (slug[:60] or "agent-project").lower()


def suggest_filename(name: Optional[str], framework: Optional[str]) -> str:
    """The ``Content-Disposition`` filename for a project download."""
    return f"{_safe_folder(name or framework or 'agent-project')}.zip"
