# multi_agent_generator/emit/base.py
"""
The fragment model shared by every framework emitter.

A generated project has to exist in two shapes - a few flat files for a small agent, a
package with a module per responsibility for a large one - and it would be a mistake to
write each framework's code generator twice to cover both. So the framework-specific
emitters here do not produce *files*. They produce :class:`Fragment` objects: a chunk of
code plus the import lines it needs. The assembler decides whether each fragment becomes
its own module or gets concatenated into one, and it computes the cross-module imports.

That split is what keeps the framework emitters small enough to read. Each one answers only
three questions - how does this framework declare a tool, how does it build an agent, how
does it wire agents into a workflow - and everything else (settings, credentials, the
entry point, the runner, tests, documentation) is written once in ``shared.py``.

Fragments are written against a small contract they can rely on being in scope, because the
assembler guarantees the imports:

``get_llm()``
    Returns the shared model client. Built once, reused.
``build_<agent_name>()``
    Returns a constructed agent. One per agent in the manifest.
``<ToolName>Tool`` / ``<tool_name>``
    The tool, in whatever form the framework wants it.
``record_call(name, arguments, result)``
    Records a tool call for later inspection.

And every emitted workflow module must define ``run_workflow(query: str) -> dict`` with at
least an ``"output"`` key. The sandbox harness looks for exactly that function, so this is
the seam between generated code and the Playground - which is the difference between a
Playground that runs the agent and one that prints its source.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Sequence

from ..core.manifest import AgentSpec, ProjectManifest, ToolSpec, WorkflowSpec
from ..frameworks._common import llm_snippet_for
from ..providers import LLMSnippet

__all__ = [
    "Fragment",
    "Emitter",
    "banner",
    "docstring",
    "indent",
    "join_blocks",
    "literal",
    "wrap_text",
]


# =============================================================================== helpers
def literal(value: object) -> str:
    """
    Render a Python literal for embedding in generated source.

    ``repr`` is used rather than string interpolation so that a role description containing
    a quote, a newline or a backslash cannot break the file it is written into. Model-authored
    text does contain all three.
    """
    return repr(value)


def indent(text: str, prefix: str = "    ") -> str:
    """Indent every non-blank line. Blank lines stay empty rather than becoming whitespace."""
    return "\n".join(f"{prefix}{line}" if line.strip() else "" for line in text.splitlines())


def wrap_text(text: str, width: int = 88) -> List[str]:
    """Soft-wrap prose for comments and docstrings, without a textwrap import per call."""
    words = str(text or "").split()
    if not words:
        return []
    lines: List[str] = []
    current = words[0]
    for word in words[1:]:
        if len(current) + 1 + len(word) <= width:
            current = f"{current} {word}"
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def docstring(summary: str, body: Sequence[str] = (), quote: str = '"""') -> str:
    """
    Build a module or function docstring.

    Generated code that explains itself is the difference between a handover and a dump, so
    every emitted module gets one of these - and it says what the module is *for*, taken from
    the manifest's purpose field, not a restatement of its filename.
    """
    summary = " ".join(str(summary or "").split())
    lines = [f"{quote}{summary}"]
    for paragraph in body:
        text = str(paragraph or "").strip()
        if not text:
            continue
        lines.append("")
        lines.extend(wrap_text(text))
    lines.append(quote)
    return "\n".join(lines)


def banner(manifest: ProjectManifest, purpose: str, extra: Sequence[str] = ()) -> str:
    """
    The provenance header every generated file carries.

    States which framework, provider and model produced it, so a file that is later pasted
    into a bug report carries its own context. No credential is ever written here - only the
    provider's *name* and the environment variable the code reads.
    """
    body: List[str] = []
    if purpose:
        body.append(purpose)
    body.extend(extra)
    body.append(
        f"Generated by multi-agent-generator for {manifest.framework} "
        f"using the {manifest.provider} provider"
        + (f" ({manifest.model})." if manifest.model else ".")
    )
    return docstring(purpose or "Generated module.", body[1:] if purpose else body)


def join_blocks(blocks: Sequence[str], separator: str = "\n\n\n") -> str:
    """Join non-empty code blocks, normalising trailing whitespace."""
    cleaned = [str(b).rstrip() for b in blocks if str(b).strip()]
    return separator.join(cleaned)


# ============================================================================== fragments
@dataclass
class Fragment:
    """
    A piece of generated code plus what it needs imported.

    ``imports`` are third-party or stdlib lines the code itself requires. Imports of *other
    generated modules* are not listed here - the assembler works those out from the manifest,
    because only it knows whether the target ended up in its own file or in the same one.
    """

    body: str = ""
    imports: List[str] = field(default_factory=list)
    #: Module-level code that must appear before ``body`` - credential resolution, for one.
    preamble: str = ""
    #: Names this fragment defines. Used to verify the plan against what was emitted.
    provides: List[str] = field(default_factory=list)

    def merge(self, other: "Fragment") -> "Fragment":
        """Combine two fragments destined for the same file."""
        return Fragment(
            body=join_blocks([self.body, other.body]),
            imports=list(dict.fromkeys([*self.imports, *other.imports])),
            preamble=join_blocks([self.preamble, other.preamble], "\n\n"),
            provides=list(dict.fromkeys([*self.provides, *other.provides])),
        )


# =============================================================================== emitters
class Emitter:
    """
    Base class for the framework-specific code emitters.

    Subclasses implement the three framework-shaped questions. Everything else has a default
    here, so adding a framework means writing three methods rather than a whole generator.

    A subclass must never guess at an API. Where a framework's real interface cannot express
    something the manifest describes - Agno taking plain callables where CrewAI wants tool
    objects, say - the emitter follows the framework and adapts the shape, rather than
    emitting code that reads well and fails on import.
    """

    #: Canonical framework key, matching the CLI's ``--framework`` values.
    key: str = ""
    #: Human-readable name for headers and documentation.
    label: str = ""
    #: Import lines the workflow module needs on top of what its fragment declares.
    workflow_imports: Sequence[str] = ()

    def __init__(self, manifest: ProjectManifest) -> None:
        self.manifest = manifest
        # The LLM snippet knows how each provider is constructed for each framework family.
        # Reusing it means a new provider is wired into the multi-file emitters and the
        # legacy single-file generators at the same time, from one place.
        self.snippet: LLMSnippet = llm_snippet_for(
            self.key or manifest.framework,
            manifest.provider,
            manifest.model or None,
        )

    # ------------------------------------------------------------------- LLM construction
    def llm_fragment(self) -> Fragment:
        """
        The shared model client.

        Built once and cached, because constructing it per step reloads a local model on
        every single call - which is the difference between a slow project and an unusable
        one for the ``huggingface-local`` provider.

        Subclasses override only when the framework wants the model as an expression handed
        to each agent rather than as a shared instance.
        """
        setup = (self.snippet.setup or "").strip()
        if not setup:
            expression = (self.snippet.expression or "None").strip()
            build_body = f"    return {expression}"
        else:
            build_body = indent(setup) + "\n    return llm"

        note = (
            f"    # NOTE: {self.snippet.comment}\n" if self.snippet.comment else ""
        )
        body = (
            "_CLIENT = None\n\n\n"
            "def build_llm():\n"
            + indent(
                docstring(
                    "Construct the model client this project's agents talk to.",
                    [
                        "Reads its credential from the environment. Nothing is hard-coded, "
                        "so this file is safe to commit and safe to share.",
                    ],
                )
            )
            + "\n"
            + note
            + build_body
            + "\n\n\n"
            "def get_llm():\n"
            + indent(
                docstring(
                    "Return the shared client, building it on first use.",
                    [
                        "Cached deliberately: building a client per step reloads a local "
                        "model every time, which makes a local-provider run unusably slow.",
                    ],
                )
            )
            + "\n"
            "    global _CLIENT\n"
            "    if _CLIENT is None:\n"
            "        _CLIENT = build_llm()\n"
            "    return _CLIENT\n"
        )
        return Fragment(
            body=body,
            imports=list(self.snippet.imports),
            preamble=(self.snippet.preamble or "").strip(),
            provides=["build_llm", "get_llm"],
        )

    # ------------------------------------------------------------------------------ tools
    def tool_fragment(self, tool: ToolSpec) -> Fragment:  # pragma: no cover - abstract
        raise NotImplementedError

    def tool_expression(self, tool: ToolSpec) -> str:
        """How a tool is referenced when handed to an agent. Usually a constructor call."""
        return f"{tool.class_name}()"

    def tool_registry_fragment(self, tools: Sequence[ToolSpec]) -> Fragment:
        """
        The registry that maps a tool name to its instance.

        Emitted so agents can be given tools by name and so a test can enumerate them, which
        is what lets ``tests/test_tools.py`` check every tool rather than a hardcoded list
        that silently stops covering new ones.
        """
        if not tools:
            return Fragment(body="TOOLS: dict = {}\n\n\ndef all_tools():\n    return []\n",
                            provides=["TOOLS", "all_tools"])
        entries = "\n".join(
            f"    {literal(t.name)}: {self.tool_expression(t)}," for t in tools
        )
        body = (
            "#: Every tool in this project, by name.\n"
            f"TOOLS = {{\n{entries}\n}}\n\n\n"
            "def all_tools():\n"
            + indent(docstring("Return every tool, for agents that take the whole set."))
            + "\n"
            "    return list(TOOLS.values())\n"
        )
        return Fragment(body=body, provides=["TOOLS", "all_tools"])

    # ------------------------------------------------------------------------------ state
    def state_fragment(self) -> Fragment:
        """
        The shared state type, for frameworks that pass an explicit state object between steps.

        Empty by default. LangGraph overrides it because its ``TypedDict`` state is the
        framework's actual contract - every node annotates it - so it needs a real module.
        The other frameworks carry their state inside the framework's own objects (a CrewAI
        crew, a Flow's ``self.state``, an executor's scratchpad), and emitting an unused state
        class for them would be a file with no reason to exist.

        Defined here rather than only on the subclass so the assembler can call it
        unconditionally instead of testing which framework it is holding.
        """
        return Fragment()

    # ----------------------------------------------------------------------------- agents
    def agent_fragment(self, agent: AgentSpec) -> Fragment:  # pragma: no cover - abstract
        raise NotImplementedError

    # --------------------------------------------------------------------------- workflow
    def workflow_fragment(self, workflow: WorkflowSpec) -> Fragment:  # pragma: no cover
        raise NotImplementedError

    # ---------------------------------------------------------------------------- helpers
    def agent_tools_expression(self, agent: AgentSpec) -> str:
        """``[TOOLS["search"], TOOLS["fetch"]]`` for the tools this agent actually holds."""
        names = [n for n in agent.tools if self.manifest.tool(n) is not None]
        if not names:
            return "[]"
        return "[" + ", ".join(f"TOOLS[{literal(n)}]" for n in names) + "]"

    def instructions_for(self, agent: AgentSpec) -> str:
        """One instruction string combining goal, backstory and responsibilities."""
        parts: List[str] = []
        if agent.goal:
            parts.append(agent.goal)
        if agent.backstory:
            parts.append(agent.backstory)
        if agent.responsibilities:
            parts.append("Responsibilities: " + "; ".join(agent.responsibilities) + ".")
        return " ".join(parts).strip()

    def step_prompt_expression(self, node_description: str, expected: str) -> str:
        """
        Build the prompt expression for one workflow step.

        Kept as an expression rather than an f-string in the template so the description and
        the expected output are embedded as literals - model-authored text with a brace or a
        quote in it must not be able to break the generated file.
        """
        pieces = [literal(node_description or "Handle the request.")]
        pieces.append('"\\n\\nUser request: " + str(query)')
        if expected:
            pieces.append(f'"\\n\\nExpected output: " + {literal(expected)}')
        return " + ".join(pieces)
