"""
Auto-generated CrewAI multi-agent system.

Provider: openai
Model:    gpt-4o-mini

Generated by multi-agent-generator. Run `multi-agent-generator --check-deps --framework crewai --provider openai`
to verify the packages this file needs are installed.
"""
from crewai import Agent, Crew, Process, Task
from crewai.tools import BaseTool
from typing import Any, Dict, List
from crewai import LLM


# Shared LLM
llm = LLM(model="gpt-4o-mini")


# Tool stubs - replace the bodies with real implementations
class SearchTool(BaseTool):
    name: str = "search_tool"
    description: str = "Tool for search_tool operations"

    def _run(self, query: str) -> str:
        # TODO: implement actual functionality
        return f"Result from search_tool: {query}"


class WebScraperTool(BaseTool):
    name: str = "web_scraper"
    description: str = "Tool for web_scraper operations"

    def _run(self, query: str) -> str:
        # TODO: implement actual functionality
        return f"Result from web_scraper: {query}"


class WritingTool(BaseTool):
    name: str = "writing_tool"
    description: str = "Tool for writing_tool operations"

    def _run(self, query: str) -> str:
        # TODO: implement actual functionality
        return f"Result from writing_tool: {query}"


class GrammarCheckerTool(BaseTool):
    name: str = "grammar_checker"
    description: str = "Tool for grammar_checker operations"

    def _run(self, query: str) -> str:
        # TODO: implement actual functionality
        return f"Result from grammar_checker: {query}"


# Tool registry
TOOLS = {
    "search_tool": SearchTool(),
    "web_scraper": WebScraperTool(),
    "writing_tool": WritingTool(),
    "grammar_checker": GrammarCheckerTool(),
}


# Agent: research_specialist
agent_research_specialist = Agent(
    role='Research Specialist',
    goal='Conduct thorough research and gather information',
    backstory='Expert researcher with years of experience in data gathering and analysis',
    verbose=True,
    allow_delegation=False,
    tools=[TOOLS["search_tool"], TOOLS["web_scraper"]],
    llm=llm,
)

# Agent: content_writer
agent_content_writer = Agent(
    role='Content Writer',
    goal='Create clear and comprehensive written content',
    backstory='Professional writer skilled in creating engaging and informative content',
    verbose=True,
    allow_delegation=False,
    tools=[TOOLS["writing_tool"], TOOLS["grammar_checker"]],
    llm=llm,
)

# Task: research_task
task_research_task = Task(
    description='Gather information and conduct research on the given topic',
    agent=agent_research_specialist,
    expected_output='Comprehensive research findings and data',
)

# Task: writing_task
task_writing_task = Task(
    description='Create written content based on research findings',
    agent=agent_content_writer,
    expected_output='Well-written content document',
)

# Crew configuration
crew = Crew(
    agents=[agent_research_specialist, agent_content_writer],
    tasks=[task_research_task, task_writing_task],
    process=Process.sequential,
    verbose=True,
)


def run_workflow(query: str):
    """Run the workflow using CrewAI."""
    return crew.kickoff(inputs={"query": query})


if __name__ == "__main__":
    print(run_workflow("Your query here"))
